stages:
  - test
  - build
  - push
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

image: gitlab/dind
services:
  - docker:dind

test:
  stage: test
  image: node:latest
  script:
    - echo "Testing..."

build_image:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE  .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY    
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master
    - pull_requests

release_image:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy_to_staging:
  stage: deploy
  environment:
    name: staging
  script:
    - echo "Deploying"
  only:
    - master