gitlab:
  clientId: GITGUD_GITLAB_CLIENT_ID
  clientSecret: GITGUD_GITLAB_CLIENT_SECRET
  accessToken: GITGUD_GITLAB_ACCESS_TOKEN
  baseUri: GITGUD_GITLAB_URI
  oauthRedirectPath: GITGUD_OAUTH_REDIRECT_PATH
kafka:
  broker: GITGUD_KAFKA_BROKER
  username: GITGUD_KAFKA_USERNAME
  password: GITGUD_KAFKA_PASSWORD
postgres:
  url: GITGUD_PG_URL
