gitgud:
  host: GITGUD_NGROK_DOMAIN
gitlab:
  client_id: GITGUD_GITLAB_CLIENT_ID
  client_secret: GITGUD_GITLAB_CLIENT_SECRET
  access_token: GITGUD_GITLAB_ACCESS_TOKEN
  uri: GITGUD_GITLAB_URI
kafka:
  broker: GITGUD_KAFKA_BROKER
  username: GITGUD_KAFKA_USERNAME
  password: GITGUD_KAFKA_PASSWORD
postgres:
  url: GITGUD_PG_URL
redis:
  url: GITGUD_REDIS_URL
