apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitgud.fullname" . }}
  labels:
    {{- include "gitgud.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "gitgud.selectorLabels" . | nindent 4 }}