replicaCount: 1

image:
  repository: gitgud
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ''
      paths:
        - path: /
          pathType: Prefix

extraEnv:
  - name: WDS_SOCKET_PORT
    value: 443
